# Generated by Django 3.1.5 on 2021-02-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('G', 'Gaming'), ('BO', 'Bogdan'), ('TE', 'Test')], max_length=3)),
                ('slug', models.SlugField(max_length=150)),
                ('image', models.ImageField(blank=True, default='none', upload_to='')),
            ],
        ),
    ]
