# Generated by Django 3.1.5 on 2021-03-04 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210304_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thubnail',
            new_name='thumbnail',
        ),
    ]
