# Generated by Django 3.1.5 on 2021-04-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
