# Generated by Django 3.1.5 on 2021-04-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(max_length=2)),
                ('skin_type', models.CharField(choices=[('NR', 'Normal'), ('OI', 'Oily'), ('DR', 'Dry'), ('IR', 'Irritated'), ('AL', 'All')], max_length=500)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
