# Generated by Django 3.1.5 on 2021-04-22 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_helpme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpme',
            options={'verbose_name_plural': 'Help Me'},
        ),
    ]
