# Generated by Django 3.1.5 on 2021-05-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20210422_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpme',
            name='age',
            field=models.IntegerField(),
        ),
    ]
