# Generated by Django 3.1.5 on 2021-05-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20210511_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'Ofte Stilte Spørsmål'},
        ),
    ]
